In [ ]:
### Bottomonium ERT implementation

import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def dag(array):
    return array.T.conj()

In [ ]:
class ERTens: #AkL list of dissapators w/ sqrt(Γ) inc.
    def __init__(self, H, AkL, dt, psiI, R=None):
        self.H = H #Hamiltonian
        self.AkL = AkL #Dissipators
        self.K = len(AkL) 
        self.dt = dt #Explicit time step
        self.psiL = np.array(psiI)
        self.R = 2*np.power(len(AkL),2) if R==None else R #Truncation size
    def Jk(self, A):
        return (-1j*H)+((self.K/2)*((A@A)-(dag(A)@A)))
    def Uk(self, A):
        return expm((self.dt*self.Jk(A))-(1j*np.sqrt(self.K*self.dt)*A))
    def Vk(self, A):
        return expm((self.dt*self.Jk(A))+(1j*np.sqrt(self.K*self.dt)*A))
    def step(self):
        nPsi = []
        for A in self.AkL:
            for psi in self.psiL:
                nPsi.append(self.Uk(A)@psi)
                nPsi.append(self.Vk(A)@psi)
        nPsi = np.array(nPsi)
        Sij = np.dot(nPsi.conj(),nPsi.T)
        w, Uuns = np.linalg.eigh(Sij)
        idx = np.argsort(w)[::-1]
        Ulk = Uuns[:,idx]
        if len(nPsi) > self.R:
            UR = Ulk.T.conj()[:self.R]/np.sqrt(2*self.K)
        else:
            UR = Ulk.T.conj()
        rPsi = UR@nPsi
        self.psiL = rPsi
    def obs(self, O):
        return np.mean(np.array([psi.conj()@O@psi for psi in self.psiL]))

In [ ]:
# Bottomonium system

In [3]:
import numpy as np

# Example: Grid in 2D
x = np.linspace(-1, 1, 5)
y = np.linspace(-1, 1, 5)
X, Y = np.meshgrid(x, y)

# Compute radial distance
r = np.sqrt(X**2 + Y**2)

# Flatten into diagonal matrix
R_matrix = np.diag(r.flatten())
print(R_matrix)


[[1.41421356 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         1.11803399 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         1.11803399 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0

In [6]:
r

array([[1.41421356, 1.11803399, 1.        , 1.11803399, 1.41421356],
       [1.11803399, 0.70710678, 0.5       , 0.70710678, 1.11803399],
       [1.        , 0.5       , 0.        , 0.5       , 1.        ],
       [1.11803399, 0.70710678, 0.5       , 0.70710678, 1.11803399],
       [1.41421356, 1.11803399, 1.        , 1.11803399, 1.41421356]])

In [7]:
import numpy as np
from scipy.sparse import block_diag

# Define blocks
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# Create block diagonal matrix
blocks = [A, B, C]
block_matrix = block_diag(blocks)

print(block_matrix.toarray())  # Convert to dense for inspection

# Multiplying with a vector
vector = np.array([1, 2, 3, 4, 5, 6])
result = block_matrix @ vector
print(result)


[[ 1  2  0  0  0  0]
 [ 3  4  0  0  0  0]
 [ 0  0  5  6  0  0]
 [ 0  0  7  8  0  0]
 [ 0  0  0  0  9 10]
 [ 0  0  0  0 11 12]]
[  5  11  39  53 105 127]
